<a href="https://colab.research.google.com/github/AritraDam/Machine_Learning_Journey/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY practice


In [2]:
import numpy as np

List vs Numpy - Time Taken (Numpy helps in faster Operations)

In [2]:
from time import process_time

Time taken by List

In [3]:
from IPython.utils import process
python_list = [i for i in range(100000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.013446776000000327


Time taken by Numpy array

In [4]:
python_numpy = np.array([i for i in range(100000)])

start_time = process_time()

python_numpy += 5

end_time = process_time()

print(end_time - start_time)


0.000422283999999884


Numpy Arrays

In [10]:
#list
list1 = [1,2,3,4,5,6]
print(list1)
print(type(list1))

#numpy array

np_array = np.array(list1)
print(np_array)
print(type(np_array))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [19]:
a = np.array([1,2,3,4,5,6,7])
print(a.shape)
b = np.array([(1,2,3,4),(1,2,3,4)])
print(b)
print(b.shape)

(7,)
[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [20]:
a = np.array([1,2,3,4], dtype= float)
print(a)

[1. 2. 3. 4.]


Initial Placeholders in numpy arrays

In [27]:
#create a numpy arrays of zeros ans ones
x = np.zeros((4,4), dtype= int)
print(x)
print()
x = np.ones((4,4))
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
x = np.full((4,4),7)
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [10]:
#identity matrix

a = np.eye(4,dtype = int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [15]:
#create a numpy array with random values
b = np.random.random((3,4)) #between 0-1
print(b)
#random integers from 10 - 100
b = np.random.randint(10,100,(4,4))
print(b)

[[0.2300683  0.53652898 0.13340176 0.75591619]
 [0.06542739 0.65166759 0.3862175  0.9518234 ]
 [0.13542064 0.75157857 0.94215965 0.53106575]]
[[99 79 73 61]
 [47 26 62 79]
 [15 84 12 85]
 [74 85 26 24]]


In [25]:
#array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)
#array of evenly spaced values --> specifying the number of steps, [start, stop)
d = np.arange(10,30,5)
print(d)

[10. 15. 20. 25. 30.]
[10 15 20 25]


In [29]:
#convert a list to a numpy array
list1 = [1,2,3,4,5,6]
e = np.array(list1)
f = np.asarray(list1)
print(e,type(e))
print(f,type(f))
#The key difference is that e is guaranteed to be a new NumPy array, whereas f
# might reuse the existing list if it was already a NumPy array.

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


Analysing a numpy array

In [36]:
c = np.random.randint(10,90,(5,5))
print(c.shape)
print(c.ndim) #dimensions
print(c.size) #size of the array
print(c.dtype) #data type of the array

(5, 5)
2
25
int64


Mathematical Operations on a numpy array

In [42]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #concatenate the lists

a = np.random.randint(1,10,(3,3))
b = np.random.randint(11,20,(3,3))
print(a)
print(b)

print(a+b) #it adds the values
print(np.add(a,b)) # also adds

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[5 5 2]
 [5 2 1]
 [2 2 8]]
[[13 16 11]
 [17 13 11]
 [18 19 12]]
[[18 21 13]
 [22 15 12]
 [20 21 20]]
[[18 21 13]
 [22 15 12]
 [20 21 20]]


Array manupulation

In [45]:
#two ways to transpose a matrix
g = np.random.randint(10,40,(3,5))
print(g.T)
g = np.transpose(g)
print(g)

[[39 33 29]
 [17 39 15]
 [35 17 13]
 [23 35 34]
 [14 16 16]]
[[39 33 29]
 [17 39 15]
 [35 17 13]
 [23 35 34]
 [14 16 16]]


In [49]:
#reshaping a array
a = np.random.randint(1,9,(2,4))
print(a)
print(a.shape)
b = a.reshape(4,2)
print(b)
print(b.shape)

[[7 8 1 4]
 [5 4 8 2]]
(2, 4)
[[7 8]
 [1 4]
 [5 4]
 [8 2]]
(4, 2)


Pandas Library:

Useful for data Processing and Analysis.

Pandas Data Frame:
Pandas DataFrame is two-dimensional tabular data structure with labled axes(rows and column)

In [2]:
#import panda library

import pandas as pd
import numpy as np

Creating a Pandas DataFrame

In [11]:
#importing the boston house price data
from sklearn.datasets import fetch_california_housing

In [6]:
california_dataset = fetch_california_housing()

In [5]:
type(california_dataset)

sklearn.utils._bunch.Bunch

In [6]:
print(california_dataset)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

In [7]:
#pandas Dataframe

california_df = pd.DataFrame(california_dataset.data,columns = california_dataset.feature_names)

In [9]:
#first 5
california_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [10]:
california_df.shape

(20640, 8)

Importing the data from a csv file to a pandas DataFrame

In [11]:
#csv file to pandas df


mnist_df = pd.read_csv('/content/sample_data/mnist_test.csv')

In [12]:
type(mnist_df)

pandas.core.frame.DataFrame

In [13]:
mnist_df.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [14]:
mnist_df.shape

(9999, 785)

Exporting a DataFrame to a CSV file

In [15]:
california_df.to_csv('california.csv')

In [3]:
# creating a dataframe with random values

rand_df = pd.DataFrame(np.random.randint(10,100,(40,34)))

In [3]:
rand_df.head()

0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  30  \
0  61  20  25  32  93  61  19  68  66  30  ...  22  30  55  44  98  97  88   
1  74  99  18  19  17  66  47  61  92  62  ...  99  19  32  54  98  94  63   
2  46  50  36  45  26  32  45  73  93  65  ...  36  65  82  63  99  21  11   
3  39  34  58  24  39  75  76  28  94  66  ...  31  51  56  65  11  42  51   
4  32  64  81  20  81  95  75  81  71  99  ...  51  30  12  41  85  27  49   

   31  32  33  
0  26  37  25  
1  74  92  58  
2  15  49  30  
3  23  29  97  
4  60  53  49  

[5 rows x 34 columns]

In [5]:
rand_df.shape

(40, 34)

In [4]:
#last five rows
rand_df.tail()

0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  30  \
35  58  88  29  46  91  53  68  78  12  85  ...  78  79  89  17  44  16  36   
36  43  32  84  53  91  53  67  37  18  66  ...  97  53  39  10  60  11  70   
37  26  34  14  41  30  21  30  19  25  50  ...  11  72  99  65  39  91  64   
38  62  47  97  63  95  47  77  57  19  90  ...  36  75  22  26  50  58  10   
39  33  40  93  36  52  52  24  22  17  66  ...  43  77  43  79  83  21  44   

    31  32  33  
35  40  64  89  
36  11  34  53  
37  37  72  57  
38  99  47  52  
39  60  30  59  

[5 rows x 34 columns]

In [9]:
#info about the data frame
california_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [10]:
# finding the number of missing values
california_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [14]:
diabetes_dp = pd.read_csv('/content/sample_data/diabetes.csv')
diabetes_dp.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [17]:
#counting the values based on the lables
diabetes_dp.value_counts('Outcome')

Outcome
0    500
1    268
dtype: int64

In [18]:
diabetes_dp.value_counts('Age')

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
38    16
36    16
32    16
45    15
34    14
40    13
43    13
46    13
39    12
35    10
52     8
44     8
50     8
51     8
58     7
54     6
47     6
53     5
60     5
49     5
57     5
48     5
66     4
62     4
63     4
55     4
59     3
56     3
65     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
dtype: int64

In [19]:
diabetes_dp.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

Statistical Measure

In [20]:
california_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [21]:
california_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [22]:
california_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [23]:
california_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [24]:
california_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [25]:
#all the statical measure at once
california_df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

Manupulating the data frame

In [26]:
california_df['price'] = california_dataset.target

In [28]:
california_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [29]:
#remove a row(axis = 0)
california_df.drop(index = 1,axis = 0)


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5      4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  price  
0        -122.23  4.526  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
5        -122.25  2.697  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20639 rows x 9 columns]

In [30]:
#drop a column(axis = 1)
california_df.drop(columns = 'price',axis = 1)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [31]:
#locating  row
california_df.iloc[1]

MedInc           8.301400
HouseAge        21.000000
AveRooms         6.238137
AveBedrms        0.971880
Population    2401.000000
AveOccup         2.109842
Latitude        37.860000
Longitude     -122.220000
price            3.585000
Name: 1, dtype: float64

In [32]:
#by column
california_df['AveRooms']

0        6.984127
1        6.238137
2        8.288136
3        5.817352
4        6.281853
           ...   
20635    5.045455
20636    6.114035
20637    5.205543
20638    5.329513
20639    5.254717
Name: AveRooms, Length: 20640, dtype: float64

In [33]:
#another method
print(california_df.iloc[:,1]) #2nd column

0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ... 
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20640, dtype: float64


Correlation:

> 1) Positive Correlation

> 2) Negative Correlation





In [35]:
california_df.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   
price       0.688075  0.105623  0.151948  -0.046701   -0.024650 -0.023737   

            Latitude  Longitude     price  
MedInc     -0.079809  -0.015176  0.688075  
HouseAge    0.011173  -0.108197  0.105623  
AveRooms    0.106389  -0.027540  0.151948  
AveBedrms   0.069721   0.013344 -0.046701  
Population -0.108785   0.099773 -0.024650  
AveOccup    0.002366   0.002476 -0.023737  
Latitude    1.000000  -0.924664 -0.144160  
Longitude  -0.924664   1.000000 -0.045967  
price      -0.144160  -0.045967  1.000000